#spring:
#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:cperf}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: ${DB_USERNAME:root}
#    password: ${DB_PASSWORD:}
#    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
#    dbcp2:
#      test-while-idle: true
#      validation-query: SELECT 1
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
spring:
  jpa:
      database: MYSQL
      hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
      url: jdbc:mysql://mysql-prod.database.svc.cluster.local:5432/cperf?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      username: cpef
      password: MGgqazV7vfs$@jkn
      driver-class-name: com.mysql.cj.jdbc.Driver
        
  jackson:
    serialization:
      fail-on-empty-beans: false
              
  mail:
      default-encoding: UTF-8
      host: smtp.gmail.com
      port: 587
      username: cperf.workgroup@gmail.com
      password: cperfsup@1
      protocol: smtp
      tls: true
      properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
  
  cperf:
    admin:
      email: ${ADMIN_EMAIL:mohamed.ali@snsoftware.com}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  
  file:
    upload-dir: ./uploads/
    img-dir: ./uploads//images/
    avatar-dir: ./uploads/images/avatars/
        
        
        